---
#- name: check ruby {{ ruby_version }} installed
#  shell: "ruby -v | grep {{ ruby_version }}"
#  register: ruby_installed
#  changed_when: false
#  ignore_errors: yes # failure means our ruby version isn't installed yet
#  always_run: yes

- name: install prerequisites
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common
    - zlib1g
    - zlib1g-dev
    # below are recommended by rbenv
    # https://github.com/sstephenson/ruby-build/wiki#suggested-build-environment
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    #- zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  #when: ruby_installed.rc != 0

- name: add brightbox repo
  apt_repository: repo=ppa:brightbox/ruby-ng state=present

- name: install ruby {{ ruby_version }}
  apt: name={{ item }} state=present
  with_items:
    - ruby{{ ruby_version }} 
    - ruby{{ ruby_version }}-dev

- name: install bundler
  gem: name=bundler user_install=no state=present

- name: install rails
  gem: name=rails version={{rails_version}} user_install=no state=present
