---
# TODO: install the rest of this stack (as separate from a hydra app)
- name: install java 7 (openjdk)
  sudo: yes
  apt: name=openjdk-7-jdk state=installed

- name: is jetty in place?
  stat: path={{ jetty_dir }}
  register: jetty_loc

- name: install jetty with solr and fedora
  sudo: no
  remote_user: "{{ deploy_user }}"
  shell: cd {{ project_dir }}; bundle exec rake jetty:clean
  when: not jetty_loc.stat.exists

- name: configure jetty with solr and fedora
  sudo: no
  remote_user: "{{ deploy_user }}"
  shell: cd {{ project_dir }}; bundle exec rake sufia:jetty:config
  when: not jetty_loc.stat.exists
  ignore_errors: True #bug from change of fedora directory

- name: move jetty to another dir (work around vagrant locking bug)
  command: mv {{ project_dir }}/jetty {{ jetty_dir }}
  when: not jetty_loc.stat.exists

## TODO: move this to a handler
#- name: start jetty (with Solr and Fedora)
#  sudo: no
#  remote_user: "{{ deploy_user }}"
#  shell: bash -lc "cd {{ project_dir }}; bundle exec rake jetty:start"
#  ignore_errors: True #most of the time stderr doesn't mean it isn't running

