---
- name: run redis-server
  service: name=redis-server state=started

- name: copy resque init script
  template: src=pool_q dest=/etc/init.d/resque-pool mode=0755

- name: start resque
  service: name=resque-pool state=started enabled=yes
