---
- name: update apt cache
  apt: update_cache=true

- name: sufia / general server prerequisites
  apt: name={{ item}} state=latest
  with_items:
    - imagemagick
    - redis-server
    - libsqlite3-dev
    - sqlite3
    - git
    - nodejs
    - unzip
    #- poppler-utils # not mentioned in sufia; ualberta uses
    #- libreoffice-headless # not mentioned in sufia; ualberta uses
    #- libreoffice # not mentioned in sufia; ualberta uses
    #- GraphicsMagick # not mentioned in sufia; ualberta uses

- name: copy fits zip
  unarchive: src=fits-0.8.4_0.zip dest=/usr/local/bin/ creates=/usr/local/bin/fits-0.8.4

- name: make fits executable
  file: path=/usr/local/bin/fits-0.8.4/fits.sh mode=0755

- name: put fits on the PATH
  sudo: no
  remote_user: "{{ deploy_user }}"
  lineinfile: dest=~/.profile line='export PATH=$PATH:/usr/local/bin/fits-0.8.4'

- name: download phantomjs tarball (for testing)
  get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2 dest=~
  when: rails_env == "development"

- name: unpack phantomjs
  unarchive: src=~/phantomjs-1.9.7-linux-x86_64.tar.bz2 dest=~ creates=~/phantomjs-1.9.7-linux-x86_64/bin/phantomjs copy=no
  when: rails_env == "development"

- name: copy phantomjs executable onto path
  shell: cp ~/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/local/bin/
  when: rails_env == "development"
